# Needed for ignoring leading whitespace in heredoc
AllCops:
  TargetRubyVersion: 2.1

# The default is 15, which is too tight
Metrics/AbcSize:
  Max: 30

# The default is 10, which is too tight
Metrics/MethodLength:
  Max: 20

# The default is 80, and MediaWiki standard is 100
Metrics/LineLength:
  Max: 100
